[package]
name = "khamura"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
nokhwa = { version = "0.10.10", default-features = false, features = ["input-v4l", "decoding"] }
async-channel = "2.5"
image = { version = "0.25.10", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
toml_edit = "0.22"
tempfile = "3"
libc = "0.2"
serde_json = "1"
mozjpeg = "0.10.13"
